### ISSUE TITLE
some comments

### ISSUE THREAD

**Issue by ricomariani** [jackpal/swiftgen4cgsql#1]
https://github.com/jackpal/swiftgen4cgsql/blob/e64e6700a8ececdfaccbdb614b7456fc9f9c54c8/SwiftGen.py#L129

I'm surprised that is needed.  The JSON tells you if the proc returns a result set.

See [opt_projection](https://cgsql.dev/json-diagram#opt_projection)  and [projection](https://cgsql.dev/json-diagram#projection) which appear for procs in the "general" or "queries" category.

Cracking the .h file is of course possible but it shouldn't be necessary.

**Comment by ricomariani** [comment]
Note it's possible to have a result set without matching the pattern there.  You get that pattern if you have a result set and you use the database.  But you can create a result set with say OUT or OUT UNION out of thin air (mock functions for tests do this a lot).  You can easily create synthetic results by looping.

If you use the JSON then you know that:

procs in the "queries" section must use the database by definition -- they consist of a single select statement.

proc in the "general" section may or may not use the database and/or have a result set but the presence of projection tells you if they have a result and [general](https://cgsql.dev/json-diagram#general) includes helpfully the field "usesDatabase" so it should all be there for you on a silver platter.

If you're looking for all result sets:

loop through queries then loop through general, that should give you all the names.

Note that different result types might have different prefixes and case conversion but in a tool like yours its normal to assume a particular result type or else add a flag for various forms you might want to handle.  You can't be expected to understand all the result types anyone might have added...

**Comment by ricomariani** [comment]
Anyway I would avoid parsing the .h file

**Comment by ricomariani** [comment]
https://github.com/facebookincubator/CG-SQL/blob/main/sources/cqljson/cqljson.py  has some other examples of using the JSON to make interesting stuffs.

**Comment by jackpal** [comment]
Thanks for the review!

I guess the `get_fetcher_decls` function is currently unused. I used it earlier to export the fetcher functions to Swift, so they could be called from Swift code directly, without generating the ref set. But since I am not shipping that feature I will just remove the function.

**Comment by ricomariani** [comment]
No problemo :D
________________________________
